<div class="fieldset-wrapper customer-information">
    <div class="fieldset-wrapper-title">
        <span class="title"><h3><?php /* @escapeNotVerified */ echo __('Detail Mail Information') ?></h3></span>
    </div>
    <br/>
    <table>
        <tbody>
        <tr>
            <td class="label"><label><?php echo __('E-Mail ID') ?></label></td>
        </tr>
        <tr>
            <td class="value"><strong><?php echo $this->getMail()->getId() ?></strong></td>
        </tr>
        <tr>
            <td class="value">&nbsp;</td>
        </tr>
        <?php if(!empty($this->getMail()->getOrderId())): ?>
            <tr>
                <td class="label"><label><?php echo __('Order ID') ?></label></td>
            </tr>
            <tr>
                <td class="value"><strong><?php echo $this->getMail()->getOrderId() ?></strong></td>
            </tr>
            <tr>
                <td class="value">&nbsp;</td>
            </tr>
        <?php endif; ?>
        <?php if(!empty($this->getMail()->getCustomerId())): ?>
            <tr>
                <td class="label"><label><?php echo __('Customer ID') ?></label></td>
            </tr>
            <tr>
                <?php $url = $this->getUrl('customer/index/edit', array('id' => $this->getMail()->getCustomerId())); ?>
                <td class="value"><strong><a href='<?php echo $url ?>'><?php echo $this->getMail()->getCustomerId() ?></a></strong></td>
            </tr>
            <tr>
                <td class="value">&nbsp;</td>
            </tr>
        <?php endif; ?>
        <tr>
            <td class="label"><label><?php echo __('Template Identifier') ?></label></td>
        </tr>
        <tr>
            <td class="value"><strong><?php echo $this->htmlEscape($this->getMail()->getTemplateIdentifier()) ?></strong></td>
        </tr>
        <tr>
            <td class="value">&nbsp;</td>
        </tr>
        <?php if(!empty($this->getMail()->getSentAt())): ?>
            <tr>
                <td class="label"><label><?php echo __('Sent at') ?></label></td>
            </tr>
            <tr>
                <td class="value"><strong><?php echo $this->getMail()->getSentAt() ?></strong></td>
            </tr>
            <tr>
                <td class="value">&nbsp;</td>
            </tr>
        <?php endif; ?>
        <?php if(!empty($this->getMail()->getDeliveryTime())): ?>
            <tr>
                <td class="label"><label><?php echo __('Scheduled delivery time') ?></label></td>
            </tr>
            <tr>
                <td class="value"><strong><?php echo $this->getMail()->getDeliveryTime() ?></strong></td>
            </tr>
            <tr>
                <td class="value">&nbsp;</td>
            </tr>
        <?php endif; ?>
        <tr>
            <td class="label"><label><?php echo __('Has been successfully sent?') ?></label></td>
        </tr>
        <tr>
            <td class="value"><strong><?php echo __($this->getMail()->getSent() ? 'Yes' : 'No') ?></strong></td>
        </tr>
        <tr>
            <td class="value">&nbsp;</td>
        </tr>
        <tr>
            <td class="label"><label><?php echo __('Recipients') ?></label></td>
        </tr>
        <tr>
            <td class="value"><strong><?php echo $this->htmlEscape(implode(', ', $this->getMail()->getRecipients())) ?></strong></td>
        </tr>
        <tr>
            <td class="value">&nbsp;</td>
        </tr>
        <tr>
            <td class="label"><label><?php echo __('Tags') ?></label></td>
        </tr>
        <tr>
            <td class="value"><strong><?php echo $this->htmlEscape(implode(', ', $this->getMail()->getTags())) ?></strong></td>
        </tr>
        <tr>
            <td class="value">&nbsp;</td>
        </tr>
        <tr>
            <td class="label"><label><?php echo __('Store View Name') ?></label></td>
        </tr>
        <tr>
            <td class="value"><strong><?php echo $this->htmlEscape($this->getStoreName()) ?></strong></td>
        </tr>
        <tr>
            <td class="value">&nbsp;</td>
        </tr>
        <tr>
            <td class="label"><label><?php echo __('Language Code') ?></label></td>
        </tr>
        <tr>
            <td class="value"><strong><?php echo $this->getMail()->getLanguageCode() ?></strong></td>
        </tr>
        <tr>
            <td class="value">&nbsp;</td>
        </tr>
        <tr>
            <td class="label"><label><?php echo __('Sender E-Mail Address') ?></label></td>
        </tr>
        <tr>
            <td class="value"><strong><?php echo $this->htmlEscape(implode(', ', $this->getMail()->getSenderMail())) ?></strong></td>
        </tr>
        <tr>
            <td class="value">&nbsp;</td>
        </tr>
        <tr>
            <td class="label"><label><?php echo __('Test mode') ?></label></td>
        </tr>
        <tr>
            <td class="value"><strong><?php echo $this->getMail()->getTestMode() ? 'Yes' : 'No' ?></strong></td>
        </tr>
        <tr>
            <td class="value">&nbsp;</td>
        </tr>
        <tr>
            <td class="label"><label><?php echo __('Tracking enabled') ?></label></td>
        </tr>
        <tr>
            <td class="value"><strong><?php echo $this->getMail()->getTrackingEnabled() ? 'Yes' : 'No' ?></strong></td>
        </tr>
        <tr>
            <td class="value">&nbsp;</td>
        </tr>
        <tr>
            <td class="label"><label><?php echo __('Tracking clicks enabled') ?></label></td>
        </tr>
        <tr>
            <td class="value"><strong><?php echo $this->getMail()->getTrackingClicksEnabled()  ? 'Yes' : 'No' ?></strong></td>
        </tr>
        <tr>
            <td class="value">&nbsp;</td>
        </tr>
        <tr>
            <td class="label"><label><?php echo __('Tracking opens enabled') ?></label></td>
        </tr>
        <tr>
            <td class="value"><strong><?php echo $this->getMail()->getTrackingOpensEnabled()  ? 'Yes' : 'No' ?></strong></td>
        </tr>
        <tr>
            <td class="value">&nbsp;</td>
        </tr>
        <?php if(!empty($this->getMail()->getTransportId())): ?>
            <tr>
                <td class="label"><label><?php echo __('Transport Id') ?></label></td>
            </tr>
            <tr><?php $transportId = htmlspecialchars($this->getMail()->getTransportId()) ?>
                <td class="value"><strong title="<?php echo $transportId ?>"><?php echo substr($transportId, 0, 30) ?>...</strong></td>
            </tr>
            <tr>
                <td class="value">&nbsp;</td>
            </tr>
        <?php endif; ?>
        <?php if(!empty($this->getMail()->getAttachments())): ?>
            <tr>
                <td class="label"><label><?php echo __('Attachments') ?></label></td>
            </tr>
            <?php foreach ($this->getMail()->getAttachments() as $attachment):
                /** @var \Shockwavemk\Mail\Base\Model\Mail\Attachment $attachment */
                ?>
            <tr>
                <td class="value"><a href="<?php echo $this->getDownloadUrl($attachment) ?>"><?php echo $attachment->getFileName() ?></a></td>
            </tr>
            <?php endforeach; ?>
            <tr>
                <td class="value">&nbsp;</td>
            </tr>
        <?php endif; ?>
        </tbody>
    </table>
</div>